#!/bin/bash

dir=$(realpath "$(dirname "${BASH_SOURCE[0]}")")
swaylockcmd="swaylock -i $dir/sunset-blurred.jpg -f"

case "$1" in
    lock)
        $swaylockcmd
        ;;
    logout)
        swaymsg exit
        ;;
    suspend)
        $swaylockcmd && systemctl suspend
        ;;
    hibernate)
        $swaylockcmd && systemctl hibernate
        ;;
    reboot)
        systemctl reboot
        ;;
    shutdown)
        systemctl poweroff
        # sudo halt
        ;;
    *)
        echo "Usage: $0 {lock|logout|suspend|hibernate|reboot|shutdown}"
        exit 2
esac

exit 0
